name: swiss_eph
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_web_plugins:
    sdk: flutter
  # geolocator: ^13.0.2
  meta: ^1.15.0
  package_info_plus: ^8.2.1
  path_provider: ^2.1.5
  sweph: ^3.2.1+2.10.3
  window_manager: ^0.4.3
  # window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/packages/sweph/assets/ephe/
